import tkinter as tk
def saludar():
    nombre = entry.get()
    label2.config(text=f"Buenas {nombre}, que tengas un gran día.")
root = tk.Tk()
root.geometry("500x200")
root.title("Ejercicio3")
label1 = tk.Label(root,text="Introduce tu nombre.")
label1.pack(pady = 5)
entry = tk.Entry(root,width=40)
entry.pack(pady = 5)
button1 = tk.Button(text="Recibe un saludo personalizado.", command=saludar)
button1.pack(pady = 5)
label2 = tk.Label(root)
label2.pack(pady = 5)
root.mainloop()